export const ERROR_CODES = {
  // Common
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',

  // Auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ACCOUNT_NOT_FOUND_OR_LOCKED: 'ACCOUNT_NOT_FOUND_OR_LOCKED',
  INVALID_REFRESH_TOKEN_FORMAT: 'INVALID_REFRESH_TOKEN_FORMAT',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_EXISTS: 'CATEGORY_SLUG_EXISTS',
  PARENT_CATEGORY_NOT_FOUND: 'PARENT_CATEGORY_NOT_FOUND',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CANNOT_MAKE_CATEGORY_ITS_OWN_PARENT: 'CANNOT_MAKE_CATEGORY_ITS_OWN_PARENT',
  CANNOT_SET_CHILD_AS_PARENT: 'CANNOT_SET_CHILD_AS_PARENT',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',

  // Image / Cloudinary
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND',
  UNAUTHORIZED_IMAGE_ACCESS: 'UNAUTHORIZED_IMAGE_ACCESS',
  INVALID_IMAGE_FILE: 'INVALID_IMAGE_FILE',
  IMAGE_SIZE_EXCEEDS_LIMIT: 'IMAGE_SIZE_EXCEEDS_LIMIT',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_EXISTS: 'PRODUCT_SLUG_EXISTS',
  PRODUCT_SKU_EXISTS: 'PRODUCT_SKU_EXISTS',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
